### ISSUE TITLE
Usage as a module returns a promise

### ISSUE THREAD

**Issue by Snaptags** [oliversalzburg/which-webstorm#4]
I just noticed that using which-webstorm as a module does not work as described in the README.
It returns a Promise instead of the string I'd expect. 

(This is not a new bug, 2.0.1 had the same behavior.)

**Comment by oliversalzburg** [comment]
Hmm, that's naughty. Seems like it never worked as documented. I see two possible solutions:

1. Implement a sync variant that behaves as advertised
2. Fix the docs 😅

**Comment by Snaptags** [comment]
I prefer both, in the indicated order 😃 I can fix this later today…

**Comment by oliversalzburg** [comment]
I just pushed an update. Let me know if that works for you 😊

**Comment by oliversalzburg** [comment]
Okay, now it's passing 😋

**Comment by Snaptags** [comment]
Thanks for the update, it is working as expected now. I suggest adding TypeScript definitions too: #5
